services:
  postgres:
    image: postgres:16
    container_name: hicroft_cx_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hicroft_cx
    ports:
      - "5432:5432"
    volumes:
      - hicroft_cx_pgdata:/var/lib/postgresql/data

volumes:
  hicroft_cx_pgdata:
